### ISSUE TITLE
Convert Bot

### ISSUE THREAD

**Issue by jb3** [Nevexo/Wumpi#3]
I'd convert your Discord.py bot into the commands module, you get a nicely formatted help command with categories and it is easy to make different plugins very quickly.

If you want I'd be happy to contribute to the bot

**Comment by Nevexo** [comment]
Oh yes please. I've been meaning to look into it.

**Comment by jb3** [comment]
I'll create a new branch 👍

**Comment by jb3** [comment]
Oh yeah, please can I be added as a contributor

**Comment by Nevexo** [comment]
Adding now. I take it you found me through my smartbot broadcast?

**Comment by Nevexo** [comment]
There ya go! Thank you again.

**Comment by jb3** [comment]
Yeah I found you throught Smartbot

**Comment by jb3** [comment]
Sadly, it seems i still don't have write permission on the repo :/

**Comment by Nevexo** [comment]
Humm.. I'll sort it tomorrow for you.

**Comment by jb3** [comment]
Ok thanks

**Comment by simmsb** [comment]
look into https://github.com/nitros12/Discord-bot_2

You can make the bot nice and modularised by using the `Bot.load_extension("path_to_extension")` function. And including setup function inside that module which takes the bot class, which calls `bot.add_cog(Module(bot))` for all modules. 

Also look into overriding the bot class to add your own setup stuff, etc
